import { ConfigState } from "../../store/configSlice";

const war3: Partial<ConfigState> = {
  teams: [
    {
      homeX: 2,
      homeY: 2,
      name: "人族",
      shortName: "人",
      color: 0xffffff,
      joinCommand: ["红"],
      icon: "/theme/war3/icons/hum.png",
      hall: "/theme/war3/halls/hum.png",
      tile: "/theme/war3/tiles/hum.png",
    },
    {
      homeX: 32,
      homeY: 2,
      name: "兽族",
      shortName: "兽",
      color: 0xffffff,
      joinCommand: ["蓝"],
      icon: "/theme/war3/icons/orc.png",
      hall: "/theme/war3/halls/orc.png",
      tile: "/theme/war3/tiles/orc.png",
    },
    {
      homeX: 2,
      homeY: 32,
      name: "不死",
      shortName: "死",
      color: 0xffffff,
      joinCommand: ["黄"],
      icon: "/theme/war3/icons/ud.png",
      hall: "/theme/war3/halls/ud.png",
      tile: "/theme/war3/tiles/ud.png",
    },
    {
      homeX: 32,
      homeY: 32,
      name: "暗夜",
      shortName: "暗",
      color: 0x333333,
      joinCommand: ["绿"],
      icon: "/theme/war3/icons/ne.png",
      hall: "/theme/war3/halls/ne.png",
      tile: "/theme/war3/tiles/ne.png",
    },
  ],
  gameName: "魔兽争霸",
  styleTheme: {
    backgroundColor: 0x333333,
    textColor: 0xffffff,
    blockColor: 0x333333,
  },
  cards: [
    {
      rate: 745,
      // 氪佬概率
      goldRate: 0,
      name: "步兵",
      level: "N",
      speed: 50,
      scale: 0.8,
      face: "/theme/war3/npcs/footman.png",
      team: "人族",
      onlyTeam: true,
      goldIgnoreTeam: true,
    },
    {
      rate: 200,
      goldRate: 0,
      name: "破法者",
      level: "R",
      speed: 150,
      scale: 1,
      face: "/theme/war3/npcs/spellBreaker.png",
      team: "人族",
      onlyTeam: true,
      goldIgnoreTeam: true,
    },
    {
      rate: 50,
      goldRate: 950,
      name: "骑士",
      level: "SR",
      speed: 400,
      scale: 1.4,
      face: "/theme/war3/npcs/knight.png",
      team: "人族",
      onlyTeam: true,
      goldIgnoreTeam: true,
    },
    {
      rate: 5,
      goldRate: 50,
      name: "大法师",
      level: "SSR",
      speed: 700,
      scale: 2,
      face: "/theme/war3/npcs/heroArchMage.png",
      team: "人族",
      onlyTeam: true,
      goldIgnoreTeam: true,
    },
    {
      rate: 745,
      goldRate: 0,
      name: "大G",
      level: "N",
      speed: 50,
      scale: 0.8,
      face: "/theme/war3/npcs/grunt.png",
      team: "兽族",
      onlyTeam: true,
      goldIgnoreTeam: true,
    },
    {
      rate: 200,
      goldRate: 0,
      name: "掠夺者",
      level: "R",
      speed: 150,
      scale: 1,
      face: "/theme/war3/npcs/raider.png",
      team: "兽族",
      onlyTeam: true,
      goldIgnoreTeam: true,
    },
    {
      rate: 50,
      goldRate: 950,
      name: "牛头人",
      level: "SR",
      speed: 400,
      scale: 1.4,
      face: "/theme/war3/npcs/tauren.png",
      team: "兽族",
      onlyTeam: true,
      goldIgnoreTeam: true,
    },
    {
      rate: 5,
      goldRate: 50,
      name: "剑圣",
      level: "SSR",
      speed: 700,
      scale: 2,
      face: "/theme/war3/npcs/heroBlademaster.png",
      team: "兽族",
      onlyTeam: true,
      goldIgnoreTeam: true,
    },
    {
      rate: 745,
      goldRate: 0,
      name: "食尸鬼",
      level: "N",
      speed: 50,
      scale: 0.8,
      face: "/theme/war3/npcs/ghoul.png",
      team: "不死",
      onlyTeam: true,
      goldIgnoreTeam: true,
    },
    {
      rate: 200,
      goldRate: 0,
      name: "石像鬼",
      level: "R",
      speed: 150,
      scale: 1,
      face: "/theme/war3/npcs/gargoyle.png",
      team: "不死",
      onlyTeam: true,
      goldIgnoreTeam: true,
    },
    {
      rate: 50,
      goldRate: 0,
      name: "冰霜巨龙",
      level: "SR",
      speed: 400,
      scale: 1.4,
      face: "/theme/war3/npcs/frostWyrm.png",
      team: "不死",
      onlyTeam: true,
      goldIgnoreTeam: true,
    },
    {
      rate: 5,
      goldRate: 50,
      name: "死亡骑士",
      level: "SSR",
      speed: 700,
      scale: 2,
      face: "/theme/war3/npcs/heroDeathKnight.png",
      team: "不死",
      onlyTeam: true,
      goldIgnoreTeam: true,
    },
    {
      rate: 745,
      goldRate: 0,
      name: "弓箭手",
      level: "N",
      speed: 50,
      scale: 0.8,
      face: "/theme/war3/npcs/archer.png",
      team: "暗夜",
      onlyTeam: true,
      goldIgnoreTeam: true,
    },
    {
      rate: 200,
      goldRate: 0,
      name: "熊德",
      level: "R",
      speed: 150,
      scale: 1,
      face: "/theme/war3/npcs/druidOfTheClaw.png",
      team: "暗夜",
      onlyTeam: true,
      goldIgnoreTeam: true,
    },
    {
      rate: 200,
      goldRate: 0,
      name: "熊德",
      level: "R",
      speed: 150,
      scale: 1,
      face: "/theme/war3/npcs/druidOfTheClaw.png",
      team: "暗夜",
      onlyTeam: true,
      goldIgnoreTeam: true,
    },
    {
      rate: 50,
      goldRate: 950,
      name: "奇美拉",
      level: "SR",
      speed: 400,
      scale: 1.4,
      face: "/theme/war3/npcs/chimaera.png",
      team: "暗夜",
      onlyTeam: true,
      goldIgnoreTeam: true,
    },
    {
      rate: 5,
      goldRate: 50,
      name: "暗影猎手",
      level: "SSR",
      speed: 700,
      scale: 2,
      face: "/theme/war3/npcs/heroDemonHunter.png",
      team: "暗夜",
      onlyTeam: true,
      goldIgnoreTeam: true,
    },
  ],
};

export default war3;
